import { describe, it } from 'vitest'

/**
 * Compatibility tests verify that future revisions of the
 * FeaturePlan contract remain backward compatible.
 *
 * These tests intentionally begin as placeholders because
 * only the initial planner contract currently exists.
 */
describe('FeaturePlan Compatibility', () => {
  describe('schema evolution', () => {
    it.todo('accepts newly added optional planner fields without breaking existing plans')

    it.todo('remains compatible with historical planner outputs')

    it.todo('supports future planner schema migrations')
  })

  describe('planner evolution', () => {
    it.todo('supports future generation modes')

    it.todo('supports future feasibility states')

    it.todo('supports future data requirement metadata')
  })

  describe('structured output compatibility', () => {
    it.todo('remains compatible with future JSON Schema revisions')

    it.todo('accepts planner output generated by newer planner versions')
  })
})
