import { z } from 'zod'

/**
 * Current bridge protocol version.
 *
 * Increment only for breaking wire-protocol changes.
 */
export const BridgeProtocolVersionSchema = z.literal(1)

/**
 * Identifies which trusted participant produced the message.
 *
 * Future participants (planner, gateway, worker, etc.)
 * can be added in later protocol versions.
 */
export const BridgeSourceSchema = z.enum(['sandbox', 'runtime'])

/**
 * Common metadata attached to every bridge message.
 *
 * The header allows the runtime to:
 * - verify protocol compatibility
 * - correlate asynchronous responses
 * - identify the sender
 * - timestamp every bridge event
 */
export const BridgeHeaderSchema = z
  .object({
    /**
     * Wire protocol version.
     */
    protocolVersion: BridgeProtocolVersionSchema,

    /**
     * Correlates responses back to requests.
     *
     * Generated by the SDK.
     */
    correlationId: z.string().uuid(),

    /**
     * Message origin.
     */
    source: BridgeSourceSchema,

    /**
     * Unix timestamp (UTC, milliseconds).
     */
    timestamp: z.number().int().nonnegative(),
  })
  .strict()
