import type { BridgeError, BridgeHeader, BridgeRequest, BridgeResponse } from '@novus/contracts'

/**
 * Client responsible for dispatching requests
 * to the Trusted Runtime.
 *
 * All BridgeRequest construction is centralized here
 * so consumers never manually assemble protocol objects.
 */
export class MessageClient {
  /**
   * Public API used by the extension.
   *
   * Example:
   *
   * await client.request(
   *   "PING_RUNTIME",
   * );
   */
  public async request(method: string, payload?: unknown): Promise<BridgeResponse | BridgeError> {
    const request: BridgeRequest = {
      kind: 'request',

      header: this.buildHeader(),

      capabilityToken: this.buildCapabilityToken(),

      method: this.buildMethod(method),

      payload,
    }

    return this.send(request)
  }

  /**
   * Dispatches a BridgeRequest through the
   * Chrome Runtime transport.
   */
  private async send(request: BridgeRequest): Promise<BridgeResponse | BridgeError> {
    return await new Promise((resolve, reject) => {
      try {
        chrome.runtime.sendMessage(request, (response: BridgeResponse | BridgeError) => {
          if (chrome.runtime.lastError !== undefined) {
            reject(new Error(chrome.runtime.lastError.message))
            return
          }

          resolve(response)
        })
      } catch (error) {
        reject(error instanceof Error ? error : new Error(String(error)))
      }
    })
  }

  /**
   * Constructs the Bridge protocol header.
   */
  private buildHeader(): BridgeHeader {
    return {
      protocolVersion: 1,

      correlationId: crypto.randomUUID(),

      source: 'runtime',

      timestamp: Date.now(),
    }
  }

  /**
   * Constructs the runtime method identifier.
   *
   * TODO(P1-B003):
   * Replace this temporary formatter with the
   * generated Runtime Method Registry.
   */
  private buildMethod(method: string): string {
    return `Novus.runtime.${method}`
  }

  /**
   * Builds the capability token attached to
   * every bridge request.
   *
   * TODO(P1-C001):
   * Replace this placeholder with a signed
   * Runtime Capability Token generated by the
   * Security Engine.
   */
  private buildCapabilityToken(): never {
    return {} as never
  }
}
