import type {
  BridgeError,
  BridgeHeader,
  BridgeRequest,
  BridgeResponse,
  BridgeRegistry,
} from '@novus/contracts'

/**
 * Client responsible for dispatching requests
 * to the Trusted Runtime.
 *
 * All BridgeRequest consytruction is centralized here
 * so consumers never manually assemble protocol objects.
 */
export class MessageClient {
  /**
   * Dispatch a strongly typed request to the Runtime.
   *
   * The payload and response types are inferred from
   * the Bridge Registry.
   */
  public async request<TMethod extends keyof BridgeRegistry>(
    method: TMethod,
    payload: BridgeRegistry[TMethod]['payload'],
  ): Promise<BridgeResponse | BridgeError> {
    const request = this.buildRequest(method, payload)

    return this.send(request)
  }

  /**
   * Constructs a BridgeRequest.
   */
  private buildRequest<TMethod extends keyof BridgeRegistry>(
    method: TMethod,
    payload: BridgeRegistry[TMethod]['payload'],
  ): BridgeRequest {
    return {
      kind: 'request',

      header: this.buildHeader(),

      capabilityToken: this.buildCapabilityToken(),

      method,

      payload,
    }
  }

  /**
   * Dispatches a BridgeRequest through the
   * Chrome Runtime transport.
   *
   * This layer intentionally remains transport-only
   * and therefore does not know about the BridgeRegistry.
   */
  private async send(request: BridgeRequest): Promise<BridgeResponse | BridgeError> {
    return await new Promise((resolve, reject) => {
      try {
        chrome.runtime.sendMessage(request, (response: BridgeResponse | BridgeError) => {
          if (chrome.runtime.lastError !== undefined) {
            reject(new Error(chrome.runtime.lastError.message))
            return
          }

          resolve(response)
        })
      } catch (error) {
        reject(error instanceof Error ? error : new Error(String(error)))
      }
    })
  }

  /**
   * Constructs the Bridge protocol header.
   */
  private buildHeader(): BridgeHeader {
    return {
      protocolVersion: 1,

      correlationId: crypto.randomUUID(),

      source: 'runtime',

      timestamp: Date.now(),
    }
  }

  /**
   * Builds the capability token attached to
   * every Bridge request.
   *
   * TODO(P1-C001):
   * Replace this placeholder with a signed
   * Runtime Capability Token generated by the
   * Security Engine.
   */
  private buildCapabilityToken(): never {
    return {} as never
  }
}
