/*
 * TODO(P1-B005):
 *
 * Verify the protocolVersion in the Bridge
 * header before accepting the response.
 *
 * This will allow future protocol upgrades
 * without breaking older extension versions.
 */

import {
  BridgeErrorSchema,
  BridgeResponseSchema,
  BRIDGE_PROTOCOL_VERSION,
  DEFAULT_BRIDGE_TIMEOUT_MS,
} from '@novus/contracts'

import { ErrorSerializer } from '../errors/ErrorSerializer.js'
import { TimeoutError } from '../errors/TimeoutError.js'

import type {
  BridgeError,
  BridgeHeader,
  BridgeRequest,
  BridgeResponse,
  BridgeRegistry,
} from '@novus/contracts'

/**
 * Client responsible for dispatching requests
 * to the Trusted Runtime.
 *
 * All BridgeRequest consytruction is centralized here
 * so consumers never manually assemble protocol objects.
 */
export class MessageClient {
  /**
   * Dispatch a strongly typed request to the Runtime.
   *
   * The payload and response types are inferred from
   * the Bridge Registry.
   */
  public async request<TMethod extends keyof BridgeRegistry>(
    method: TMethod,
    payload: BridgeRegistry[TMethod]['payload'],
    timeoutMs = DEFAULT_BRIDGE_TIMEOUT_MS,
  ): Promise<BridgeResponse | BridgeError> {
    const request = this.buildRequest(method, payload)

    return this.withTimeout(this.send(request), timeoutMs)
  }

  /**
   * Constructs a BridgeRequest.
   */
  private buildRequest<TMethod extends keyof BridgeRegistry>(
    method: TMethod,
    payload: BridgeRegistry[TMethod]['payload'],
  ): BridgeRequest {
    return {
      kind: 'request',

      header: this.buildHeader(),

      capabilityToken: this.buildCapabilityToken(),

      method,

      payload,
    }
  }

  /**
   * Dispatches a BridgeRequest through the
   * Chrome Runtime transport.
   *
   * This layer intentionally remains transport-only
   * and therefore does not know about the BridgeRegistry.
   */
  private async send(request: BridgeRequest): Promise<BridgeResponse | BridgeError> {
    return await new Promise((resolve, reject) => {
      try {
        chrome.runtime.sendMessage(request, (response: BridgeResponse | BridgeError) => {
          if (chrome.runtime.lastError !== undefined) {
            reject(new Error(chrome.runtime.lastError.message))
            return
          }

          if (response === undefined) {
            reject(new Error('No Bridge response received.'))

            return
          }

          const success = BridgeResponseSchema.safeParse(response)

          if (success.success) {
            resolve(success.data)
            return
          }

          const failure = BridgeErrorSchema.safeParse(response)

          if (failure.success) {
            // 1. Extract the internal error contract from parsed success data
            const runtimeError = ErrorSerializer.deserialize(failure.data.error)

            // 2. Reject the promise instead of resolving it
            reject(runtimeError)
            return
          }

          reject(new Error('Received malformed Bridge response.'))
        })
      } catch (error) {
        reject(error instanceof Error ? error : new Error(String(error)))
      }
    })
  }

  /**
   * Constructs the Bridge protocol header.
   */
  private buildHeader(): BridgeHeader {
    return {
      protocolVersion: BRIDGE_PROTOCOL_VERSION,

      correlationId: crypto.randomUUID(),

      source: 'runtime',

      timestamp: Date.now(),
    }
  }

  /**
   * Races an asynchronous transport operation
   * against a strict timeout.
   *
   * The returned Promise rejects with a
   * TimeoutError if the operation fails to
   * complete before the configured deadline.
   */
  private async withTimeout<T>(operation: Promise<T>, timeoutMs: number): Promise<T> {
    let timeoutId: ReturnType<typeof setTimeout> | undefined

    try {
      return await Promise.race([
        operation,

        new Promise<T>((_, reject) => {
          timeoutId = setTimeout(() => {
            reject(new TimeoutError(timeoutMs))
          }, timeoutMs)
        }),
      ])
    } finally {
      if (timeoutId !== undefined) {
        clearTimeout(timeoutId)
      }
    }
  }

  /**
   * Builds the capability token attached to
   * every Bridge request.
   *
   * TODO(P1-C001):
   * Replace this placeholder with a signed
   * Runtime Capability Token generated by the
   * Security Engine.
   */
  private buildCapabilityToken(): never {
    return {} as never
  }
}
