import { z } from 'zod'

/* -------------------------------------------------------------------------- */
/*                               Token Usage                                  */
/* -------------------------------------------------------------------------- */

/**
 * Token accounting returned by the LLM provider.
 *
 * These values are used exclusively for telemetry,
 * billing estimation and capacity planning.
 *
 * They never contain user content.
 */
export const TraceTokenUsageSchema = z
  .object({
    /**
     * Tokens consumed by the prompt.
     */
    promptTokens: z.number().int().nonnegative(),

    /**
     * Tokens generated by the model.
     */
    completionTokens: z.number().int().nonnegative(),

    /**
     * Total billable tokens.
     *
     * Usually equals:
     *
     * promptTokens + completionTokens
     */
    totalTokens: z.number().int().nonnegative(),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                              Performance                                   */
/* -------------------------------------------------------------------------- */

/**
 * Runtime performance metrics.
 *
 * These measurements help identify
 * slow providers or regressions in
 * prompt execution time.
 */
export const TracePerformanceSchema = z
  .object({
    /**
     * End-to-end generation latency.
     *
     * Measured in milliseconds.
     */
    latencyMs: z.number().int().nonnegative(),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                  Billing                                   */
/* -------------------------------------------------------------------------- */

/**
 * Estimated generation cost.
 *
 * Cost is recorded independently from
 * provider invoices so historical
 * analytics remain reproducible.
 */
export const TraceBillingSchema = z
  .object({
    /**
     * Estimated USD cost.
     */
    estimatedCostUsd: z.number().nonnegative(),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                  Metrics                                   */
/* -------------------------------------------------------------------------- */

/**
 * Operational metrics describing
 * the execution cost of a generation.
 *
 * Metrics are intentionally separated
 * from evaluation scores.
 */
export const TraceMetricsSchema = z
  .object({
    tokenUsage: TraceTokenUsageSchema,

    performance: TracePerformanceSchema,

    billing: TraceBillingSchema,
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                 Evaluation                                 */
/* -------------------------------------------------------------------------- */

/**
 * AI quality evaluation.
 *
 * These scores are produced by
 * automated evaluation pipelines
 * and never contain user content.
 */
export const TraceEvaluationSchema = z
  .object({
    /**
     * Overall UI completeness.
     *
     * Range:
     * 0.0 – 1.0
     */
    uiCompleteness: z.number().min(0).max(1),

    /**
     * Accessibility score.
     *
     * Optional because not every
     * generation executes the
     * accessibility evaluator.
     */
    accessibilityScore: z.number().min(0).max(1).optional(),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                  Metadata                                  */
/* -------------------------------------------------------------------------- */

/**
 * Immutable identity for a single
 * AI generation attempt.
 *
 * This section intentionally contains
 * no operational metrics or user data.
 */
export const TraceMetadataSchema = z
  .object({
    /**
     * Globally unique trace identifier.
     */
    traceId: z.string().uuid(),

    /**
     * Anonymous installation fingerprint.
     *
     * This is a salted, irreversible hash
     * generated during extension setup.
     *
     * It is NOT:
     * - User ID
     * - Email
     * - IP address
     */
    installationFingerprint: z.string().min(32).max(128),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                               Configuration                                */
/* -------------------------------------------------------------------------- */

/**
 * Configuration used for this
 * generation attempt.
 *
 * Captures only execution configuration,
 * never user content.
 */
export const TraceConfigurationSchema = z
  .object({
    /**
     * AI provider.
     *
     * Example:
     * google
     * openai
     * anthropic
     */
    providerId: z.string().min(1).max(50),

    /**
     * Concrete model identifier.
     */
    modelId: z.string().min(1).max(100),

    /**
     * Prompt template version.
     */
    promptVersion: z.string().min(1).max(50),

    /**
     * Generation pipeline selected
     * by the planner.
     */
    generationMode: z.enum(['trusted_spec', 'generated_bundle']),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                  Outcome                                   */
/* -------------------------------------------------------------------------- */

/**
 * High-level lifecycle status.
 */
export const TraceStatusSchema = z.enum([
  'success',
  'validation_failed',
  'generation_failed',
  'rejected_by_planner',
])

/**
 * Pipeline stage where the
 * generation completed or failed.
 */
export const TraceStageSchema = z.enum(['planner', 'generator', 'compiler', 'gateway', 'runtime'])

/**
 * Final execution outcome.
 *
 * Separating status from stage gives
 * significantly better observability.
 */
export const TraceOutcomeSchema = z
  .object({
    /**
     * Overall execution result.
     */
    status: TraceStatusSchema,

    /**
     * Final pipeline stage reached.
     */
    stage: TraceStageSchema,

    /**
     * Stable machine-readable
     * failure identifier.
     *
     * Examples:
     * INVALID_MICRO_APP
     * TOKEN_LIMIT
     * GATEWAY_TIMEOUT
     */
    failureCode: z.string().min(1).max(100).optional(),
  })
  .strict()
  .superRefine((outcome, ctx) => {
    if (outcome.status === 'success' && outcome.failureCode !== undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['failureCode'],
        message: 'Successful traces cannot contain a failureCode.',
      })
    }

    if (outcome.status !== 'success' && outcome.failureCode === undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['failureCode'],
        message: 'Failed traces must include a failureCode.',
      })
    }
  })

/* -------------------------------------------------------------------------- */
/*                                  Artifact                                  */
/* -------------------------------------------------------------------------- */

/**
 * References to artifacts produced by the
 * generation pipeline.
 *
 * Only irreversible hashes are stored.
 * Raw generated code is never persisted
 * inside telemetry.
 */
export const TraceArtifactSchema = z
  .object({
    /**
     * SHA-256 hash of the generated source
     * used to build the BundleArtifact.
     *
     * Optional because failed generations
     * may never produce an artifact.
     */
    artifactSourceHash: z
      .string()
      .regex(/^[a-fA-F0-9]{64}$/, 'artifactSourceHash must be a valid SHA-256 hash.')
      .optional(),
  })
  .strict()

/* -------------------------------------------------------------------------- */
/*                                  Privacy                                   */
/* -------------------------------------------------------------------------- */

/**
 * Privacy-controlled information.
 *
 * FIX-009 requires that all potentially
 * sensitive fields live inside this
 * schema so they can be audited easily.
 */
export const TracePrivacySchema = z
  .object({
    /**
     * Indicates whether the user has
     * explicitly consented to diagnostic
     * prompt collection.
     */
    hasUserOptIn: z.boolean().default(false),

    /**
     * SHA-256 hash of the selected text.
     *
     * The original text is NEVER stored.
     */
    selectedTextHash: z
      .string()
      .regex(/^[a-fA-F0-9]{64}$/, 'selectedTextHash must be a valid SHA-256 hash.')
      .optional(),

    /**
     * Character count of the selected text.
     *
     * Useful for analytics without exposing
     * the content itself.
     */
    selectedTextCharCount: z.number().int().nonnegative().optional(),

    /**
     * Optional diagnostic prompt.
     *
     * Only available when the user has
     * explicitly opted into telemetry.
     */
    diagnosticPrompt: z.string().min(1).max(20_000).optional(),
  })
  .strict()
  .superRefine((privacy, ctx) => {
    /**
     * FIX-009:
     * Diagnostic prompts may never be stored
     * without explicit user consent.
     */
    if (!privacy.hasUserOptIn && privacy.diagnosticPrompt !== undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['diagnosticPrompt'],
        message: 'diagnosticPrompt requires explicit user opt-in.',
      })
    }

    /**
     * If no text hash exists there should be
     * no associated character count.
     */
    if (privacy.selectedTextHash === undefined && privacy.selectedTextCharCount !== undefined) {
      ctx.addIssue({
        code: z.ZodIssueCode.custom,
        path: ['selectedTextCharCount'],
        message: 'selectedTextCharCount requires selectedTextHash.',
      })
    }
  })

/* -------------------------------------------------------------------------- */
/*                            Schema Version                                  */
/* -------------------------------------------------------------------------- */

/**
 * Current GenerationTrace contract version.
 */
export const GenerationTraceSchemaVersionSchema = z.literal(1)

/* -------------------------------------------------------------------------- */
/*                           Generation Trace                                 */
/* -------------------------------------------------------------------------- */

/**
 * Immutable audit record describing a single
 * AI generation attempt.
 *
 * This contract intentionally excludes all
 * raw workspace data and acts as the final
 * privacy firewall before telemetry is stored.
 */
export const GenerationTraceBaseSchema = z
  .object({
    /**
     * Contract version.
     */
    schemaVersion: GenerationTraceSchemaVersionSchema,

    /**
     * Immutable trace identity.
     */
    metadata: TraceMetadataSchema,

    /**
     * Generation configuration.
     */
    configuration: TraceConfigurationSchema,

    /**
     * Final execution outcome.
     */
    outcome: TraceOutcomeSchema,

    /**
     * Operational telemetry.
     *
     * May be absent if generation failed
     * before the provider responded.
     */
    metrics: TraceMetricsSchema.optional(),

    /**
     * Optional automated quality scores.
     */
    evaluation: TraceEvaluationSchema.optional(),

    /**
     * Generated artifact references.
     */
    artifact: TraceArtifactSchema,

    /**
     * Privacy-controlled information.
     */
    privacy: TracePrivacySchema,
  })
  .strict()

export const GenerationTraceSchema = GenerationTraceBaseSchema.superRefine((trace, ctx) => {
  /* ------------------------------------------------------ */
  /* Successful generations should produce an artifact.      */
  /* ------------------------------------------------------ */

  if (trace.outcome.status === 'success' && trace.artifact.artifactSourceHash === undefined) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['artifact', 'artifactSourceHash'],
      message: 'Successful generations must produce an artifact hash.',
    })
  }

  /* ------------------------------------------------------ */
  /* Failed generations should not expose evaluation.        */
  /* ------------------------------------------------------ */

  if (trace.outcome.status !== 'success' && trace.evaluation !== undefined) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['evaluation'],
      message: 'Evaluation scores are only valid for successful generations.',
    })
  }

  /* ------------------------------------------------------ */
  /* Metrics should exist whenever an artifact exists.       */
  /* ------------------------------------------------------ */

  if (trace.artifact.artifactSourceHash !== undefined && trace.metrics === undefined) {
    ctx.addIssue({
      code: z.ZodIssueCode.custom,
      path: ['metrics'],
      message: 'Artifact-producing generations must include metrics.',
    })
  }
})
